export const soundMap: Record<string, string> = {
  '✨': 'sparkles.mp3',
  '🍌': 'banana.mp3',
  '🍎': 'crunchy-bite.mp3',
  '🍕': 'pizza.mp3',
  '🍦': 'lick.mp3',
  '🍺': 'beer.mp3',
  '�': 'tada.mp3',
  '🎊': 'yahoo.mp3',
  '🎶': 'yodel.mp3',
  '🐮🛎️': 'gotta-have-more-cowbell.mp3',
  '👋👋👋': 'bye-bye-bye.mp3',
  '👏': 'applause.mp3',
  '💥': '10-mario-died.mp3',
  '🔔': 'boxing-bell.mp3',
  '🤕': 'ooof.mp3',
  '🤖': 'technologia.mp3',
  '🥕': 'bite.mp3',
  '🥛': 'pour.mp3',
  '🥤': 'slurp2.mp3',
  '🦗': 'cricket.mp3',
  '🧃': 'slurp.mp3',
  '🧽🎻': 'spongebob-fail.mp3',
  '🫐': 'blue.mp3',
  '😞': 'loser.mp3',
  '😢': 'sad-trombone.mp3',
  '😮': 'wow.mp3',
  '😱': 'nooo.mp3',
  '😲': 'wow-incredible.mp3',
  '😵‍💫': 'wait-what.mp3',
  '🙋🏻‍♂️': 'hello-there.mp3',
};

export const emojis = Object.keys(soundMap);
